name: RustOS CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  TARGET: aarch64-unknown-none-softfloat

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: aarch64-unknown-none-softfloat
        components: rust-src, llvm-tools-preview
        
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
        save-always: true
        
    - name: Cache target directory
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-
        save-always: true
        
    - name: Install additional tools
      run: |
        cargo install cargo-binutils
        sudo apt-get update
        sudo apt-get install -y qemu-system-aarch64
        
    - name: Build kernel
      run: make kernel
      
    - name: Build test binaries
      run: |
        cargo build --target $TARGET --bin kernel_tests
        cargo build --target $TARGET --bin syscall_tests
        cargo build --target $TARGET --bin stress_tests
        
    - name: Upload kernel binary
      uses: actions/upload-artifact@v4
      with:
        name: kernel-binary
        path: target/${{ env.TARGET }}/debug/kernel
        if-no-files-found: error
        
    - name: Upload test binaries
      uses: actions/upload-artifact@v4
      with:
        name: test-binaries
        path: |
          target/${{ env.TARGET }}/debug/kernel_tests
          target/${{ env.TARGET }}/debug/syscall_tests
          target/${{ env.TARGET }}/debug/stress_tests
        if-no-files-found: error

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-aarch64
        
    - name: Download kernel binary
      uses: actions/download-artifact@v4
      with:
        name: kernel-binary
        path: target/${{ env.TARGET }}/debug/

    - name: Download test binaries
      uses: actions/download-artifact@v4
      with:
        name: test-binaries
        path: target/${{ env.TARGET }}/debug/
        
    - name: Make binaries executable
      run: chmod +x target/${{ env.TARGET }}/debug/*
      
    - name: Run kernel unit tests
      run: |
        set -euo pipefail
        timeout 180 qemu-system-aarch64 \
          -machine virt \
          -cpu cortex-a72 \
          -smp 4 \
          -m 2G \
          -serial stdio \
          -display none \
          -kernel target/${{ env.TARGET }}/debug/kernel_tests \
          || (echo "Kernel unit tests failed or timed out" && exit 1)
    
    - name: Run syscall integration tests
      run: |
        set -euo pipefail
        timeout 180 qemu-system-aarch64 \
          -machine virt \
          -cpu cortex-a72 \
          -smp 4 \
          -m 2G \
          -serial stdio \
          -display none \
          -kernel target/${{ env.TARGET }}/debug/syscall_tests \
          || (echo "Syscall integration tests failed or timed out" && exit 1)

    - name: Run stress tests
      run: |
        set -euo pipefail
        timeout 300 qemu-system-aarch64 \
          -machine virt \
          -cpu cortex-a72 \
          -smp 4 \
          -m 2G \
          -serial stdio \
          -display none \
          -kernel target/${{ env.TARGET }}/debug/stress_tests \
          || (echo "Stress tests failed or timed out" && exit 1)

    - name: Smoke test kernel boot
      run: |
        set -euo pipefail
        timeout --preserve-status 60 qemu-system-aarch64 \
          -machine virt \
          -cpu cortex-a72 \
          -smp 4 \
          -m 2G \
          -serial stdio \
          -display none \
          -kernel target/${{ env.TARGET }}/debug/kernel \
          > boot.log || true
        grep -q "Microkernel initialization complete" boot.log

  release:
    name: Build Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: aarch64-unknown-none-softfloat
        components: rust-src, llvm-tools-preview
        
    - name: Install required tools
      run: make setup
        
    - name: Build release kernel
      run: make release
      
    - name: Create bootable image
      run: make image
      
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-kernel
        path: |
          target/${{ env.TARGET }}/release/kernel
          target/${{ env.TARGET }}/release/image/kernel8.img
        if-no-files-found: error

  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-aarch64
        
    - name: Download test binaries
      uses: actions/download-artifact@v4
      with:
        name: test-binaries
        path: target/${{ env.TARGET }}/debug/
        
    - name: Make binaries executable
      run: chmod +x target/${{ env.TARGET }}/debug/*
      
    - name: Run performance tests
      run: |
        timeout 600 qemu-system-aarch64 \
          -machine virt \
          -cpu cortex-a72 \
          -smp 4 \
          -m 2G \
          -serial stdio \
          -display none \
          -kernel target/${{ env.TARGET }}/debug/stress_tests \
          -semihosting-config enable=on,target=native \
          > performance_results.txt || echo "Performance tests completed"
          
    - name: Upload performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: performance_results.txt

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: aarch64-unknown-none-softfloat
        components: rust-src
        
    - name: Clone uutils/coreutils
      run: git clone https://github.com/uutils/coreutils.git
      
    - name: Build coreutils for ARM64
      run: |
        cd coreutils
        cargo build --target $TARGET --features unix || echo "Coreutils build attempted"
        
    - name: Test basic integration
      run: echo "Integration tests would verify coreutils compatibility"
